# https://taskfile.dev

version: '3'

vars:
  DATABASE_URL: "postgres://postgres:postgres@localhost:5432/adopet"

tasks:
  run:
    cmds:
      - docker-compose up -d --build

  integration-test:
    cmds:
      - docker-compose up -d --build db
      - go test -v ./internal/database/...
      - docker-compose down
    env:
      DATABASE_URL: "{{.DATABASE_URL}}"

  e2e-test:
    cmds:
      - docker-compose up -d --build db
      - go test -v ./e2e/...
      - docker-compose down
    env:
      DATABASE_URL: "{{.DATABASE_URL}}"
